
export default function Articles() {

    return (
        [
            {
                title: 'The Quaking Mess',
                body: 'So far as I can tell, the closest thing to a reliable anchor in this situation is the rhythm of breath entering and departing my lungs. Funny, the way it straddles the line between voluntary and not — unoffended if I lose myself in a vortex of fearful uncertainty, but as willing as anything to lend me control over its vacillation so long as I\'ve the presence of mind to remember I can. It asks only that I refrain from fixing it in place, like a firm but subtle warning we owe the world our transience if we insist on taking part in it.<br /><br />I look to my loved ones and to what awaits on the horizon, and the miles and years that threaten to rend them irreparably — and a noxious sorrow disperses through the top of my chest like the ever-present nocturnal comfort of a child\'s stuffed animal has caught flame and turned entirely to ash. A fleeting attempt at rationalizing closure — but it feels insincere, disrespectful, premature; the grief asserts its toll unswervingly. For what do I grieve? The years are long past since I\'d been afforded the plush, sentimental comforts for which this nostalgia aches. I suppose that in itself may be the answer. I can never tell how well the veneer of aggression serves me, even in times like this when I set it aside to look at. It\'s taken for granted as a male characteristic — to retaliate against existential imperilment with gritted teeth and... what? Sword in hand? A grenade? We mistake this modern spiritual miasma for the beasts of ages past, but see too clearly what ruin abandonment of the misunderstanding would conjure.<br /><br />Whatever becomes the foundation upon which I construct my material shrine to peace and splendor will not deserve it. My sole recourse, it seems, is to be grateful — as they were in the old days for the water and for the land, and for the sun and the sky and the wind. The whole mass leeches from itself like an enormous ode to masturbation; a cosmic juxtaposition of beauty and hideousness.'
            },
            {
                title: 'Pride and Promotion',
                body: 'The time has more or less arrived where I\'m finding myself flush against the imperative of marketing, promoting, sharing, discussing, and otherwise propogating the knowledge that Dancing Through the Labyrinth exists and is worth people\'s attention. It\'s my suspicion that authors torture themselves with the task of begging and pleading for representation from professional agents not because they thirst for some veneer of prestige or because they\'re actually stuck on the notion that anything other than traditional publishing is somehow fundamentally illegitimate — but because agents serve to absorb the shame and fretfulness associated with pushing one\'s work to audiences independently. The average disposition of the authors I\'ve encountered seems to be diametrically opposed to what they perceive as the mortal imperilment of doing anything other than the writing itself to the end of having others read theirs.<br /><br />This is understandable enough. Long hours engaged in solitudinous contemplation to create what will ostensibly transmit the nuance of one\'s conscience in the highest conceivable resolution with the same social risk as dropping a signed note from an airplane lends itself overwhelmingly to execution by those unenchanted with the necessary evils of brightly-colored, short-form appeals for engagement. That being said — I\'m forced in the final analysis to conclude that the lack of faith inherent to one who\'d shun the prospect of putting themselves out there on behalf of their writing has simply yet to bleed the necessary minimum before choicelessly regarding it with a degree of reverence indistinguishable from that for a loved one.<br /><br />If unremitting exposure was the sole hope to keep your loved ones alive and thriving — would you remain so proud?'
            },
            {
                title: 'Checks and Balances',
                body: 'Bragging is a thing others are supposed to do about you. There is a fine line between that affecting mechanism with which one seeks to explicitly impress the splendor of some feat, and the absolute certainty of a declaration made without concern for anything divorced from its intrinsic function. The latter resides in the domain of what\'s conscionably undertaken; the former, no matter how it struggles to pry itself from between one\'s lips — is only rightfully manifest at the behest of one to whom it does not pertain.<br /><br />Imagine a fish that did not just swim, but all the while called attention to the marvel of its gills, the organic ingenuity of its swim bladder, and the elegance of its course through and about the water\'s currents. Even the most composed among us wouldn\'t be surprised to find themselves projecting the image of it helplessly writhing in the open air against the canvas of their consciousness. This urge betrays no evil, but is an acknowledgment of what great invisible threads bind and balance the contents of the living world — that any of its finite tendrils keeps from saturating the environment to the point of putridity. It is not that it\'s wise to wield the threat of this calibrating tendency, but actually that for those who\'re aware of the power it contains — allowing the matter of virulent boasting to proliferate unchecked is a sad disservice to one\'s fellow beings.'
            },
            {
                title: 'Another Afternoon',
                body: 'I think embracing boredom is really important. I\'m sat here in my buddy\'s cabin, just finished putting this website together, and all I have left to do is craft some more blog posts so the dice don\'t roll less than a respectable handful of times before you get a repeat. It\'s times like this — between the people, and the formatting, and the code, and everything else that isn\'t writing, when it\'s my time to sit down and do the thing I know I\'m meant to, comes the unbridled weight of boredom crashing down on my shoulders like the heavy palms of some unwelcome relative who\'s slithered up behind me.<br /><br />The first instinct is obviously evasion, into social media and food and aimless anxiety, but I\'m reminded of what forced my pen (hand and self in tow) across what first few pages I autonomously wrote: a staunch, spiteful refusal to let the bothersome thick between preoccupations of circumstance molest the time I\'d rightfully annexed as my own — and as assuredly as the scrawling in those silent rooms swept me away then, does the tapping alongside this fireplace, on the cusp of winter in northwestern Pennsylvania, just now. For as much as I feel this is what I\'m meant to do, it\'s astonishing how often I\'m deceived by what can only be described as ambient worry into reflexively groping after the Muse, who\'s guided me unreservedly whenever I sought to distill my world to the shapely confines of the written word. Sometimes I think her too patient with me — but then I\'ve been a supplicant before her since first we met.<br /><br />I\'m not at all angry she takes no physical form beyond the itching in my fingers. More convenient that way, really.'
            },
            {
                title: 'You Rolled a One! Or Rather, THE One',
                body: 'If you haven\'t figured it out yet, this is my blog. The reason it\'s designed so... what most might insist abhorrently — without any dedicated features to share or track the various entries, is twofold.<br><br>...Maybe threefold.<br><br>The second reason is because the year is 2023 and I refuse to believe it\'s the case that people actually read blogs — much less those of the meandering, philosophical variety. The first reason is because it\'s MINE, and I do what I please. The third reason is because for all the petty "merits" a blog offers an author, I\'ve been made to understand the virtue of a custom that does not so easily (as the others) crumple beneath the gravity of the fact I\'m piloting a pretentious sort of public journal.<br><br>That\'s that before expecting anyone to invest their time and money into my book, it\'s good manners to render myself bare in little snippets like this; these dice are my faithful attempt to prove I am sufficiently literate to string words together in a way that isn\'t viscerally offensive to the good, scrupulous grammarians of the English-speaking internet. That, however, is absolutely extraneous to the matter of the blog\'s organization, and alas I find the sole option of an unguided dive into all of what I might feel like presenting here, immeasurably favorable. With no temporal or thematic framework to bind these contributions into any sort of linear progression, it\'s impossible for me to exercise less than complete diligence as I paint the many sides of these dice. The early days and the later days shall all be judged as one.<br><br>Do take care!'
            }
        ]
    );
}