
export default function Articles() {

    return (
        [
            {
                title: 'Another Afternoon',
                body: 'I think embracing boredom is really important. I\'m sat here in my buddy\'s cabin, just finished putting this website together, and all I have left to do is craft some more blog posts so the dice don\'t roll less than a respectable handful of times before you get a repeat. It\'s times like this — between the people, and the formatting, and the code, and everything else that isn\'t writing, when it\'s my time to sit down and do the thing I know I\'m meant to, comes the unbridled weight of boredom crashing down on my shoulders like the heavy palms of some unwelcome relative who\'s slithered up behind me.<br /><br />The first instinct is obviously evasion, into social media and food and aimless anxiety, but I\'m reminded of what forced my pen (hand and self in tow) across what first few pages I autonomously wrote: a staunch, spiteful refusal to let the bothersome thick between preoccupations of circumstance molest the time I\'d rightfully annexed as my own — and as assuredly as the scrawling in those silent rooms swept me away then, does the tapping alongside this fireplace, on the cusp of winter in northwestern Pennsylvania, just now. For as much as I feel this is what I\'m meant to do, it\'s astonishing how often I\'m deceived by what can only be described as ambient worry into reflexively groping after the Muse, who\'s guided me unreservedly whenever I sought to distill my world to the shapely confines of the written word. Sometimes I think her too patient with me — but then I\'ve been a supplicant before her since first we met.<br /><br />I\'m not at all angry she takes no physical form beyond the itching in my fingers. More convenient that way, really.'
            },
            {
                title: 'You Rolled a One! Or Rather, THE One',
                body: 'If you haven\'t figured it out yet, this is my blog. The reason it\'s designed so... what most might insist abhorrently — without any dedicated features to share or track the various entries, is twofold.<br><br>...Maybe threefold.<br><br>The second reason is because the year is 2023 and I refuse to believe it\'s the case that people actually read blogs — much less those of the meandering, philosophical variety. The first reason is because it\'s MINE, and I do what I please. The third reason is because for all the petty "merits" a blog offers an author, I\'ve been made to understand the virtue of a custom that does not so easily (as the others) crumple beneath the gravity of the fact I\'m piloting a pretentious sort of public journal.<br><br>That\'s that before expecting anyone to invest their time and money into my book, it\'s good manners to render myself bare in little snippets like this; these dice are my faithful attempt to prove I am sufficiently literate to string words together in a way that isn\'t viscerally offensive to the good, scrupulous grammarians of the English-speaking internet. That, however, is absolutely extraneous to the matter of the blog\'s organization, and alas I find the sole option of an unguided dive into all of what I might feel like presenting here, immeasurably favorable. With no temporal or thematic framework to bind these contributions into any sort of linear progression, it\'s impossible for me to exercise less than complete diligence as I paint the many sides of these dice. The early days and the later days shall all be judged as one.<br><br>Do take care!'
            }
        ]
    );
}